/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReviewRouteImport } from './routes/dashboard/review'
import { Route as DashboardKanbanRouteImport } from './routes/dashboard/kanban'
import { Route as DashboardFocusRouteImport } from './routes/dashboard/focus'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as DashboardKanbanIndexRouteImport } from './routes/dashboard/kanban/index'
import { Route as DashboardKanbanBoardIdRouteImport } from './routes/dashboard/kanban/$boardId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewRoute = DashboardReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKanbanRoute = DashboardKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFocusRoute = DashboardFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKanbanIndexRoute = DashboardKanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardKanbanRoute,
} as any)
const DashboardKanbanBoardIdRoute = DashboardKanbanBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => DashboardKanbanRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/kanban': typeof DashboardKanbanRouteWithChildren
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/kanban/$boardId': typeof DashboardKanbanBoardIdRoute
  '/dashboard/kanban/': typeof DashboardKanbanIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/kanban/$boardId': typeof DashboardKanbanBoardIdRoute
  '/dashboard/kanban': typeof DashboardKanbanIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/kanban': typeof DashboardKanbanRouteWithChildren
  '/dashboard/review': typeof DashboardReviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/kanban/$boardId': typeof DashboardKanbanBoardIdRoute
  '/dashboard/kanban/': typeof DashboardKanbanIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/focus'
    | '/dashboard/kanban'
    | '/dashboard/review'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/kanban/$boardId'
    | '/dashboard/kanban/'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/focus'
    | '/dashboard/review'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/kanban/$boardId'
    | '/dashboard/kanban'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/focus'
    | '/dashboard/kanban'
    | '/dashboard/review'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/dashboard/kanban/$boardId'
    | '/dashboard/kanban/'
    | '/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review': {
      id: '/dashboard/review'
      path: '/review'
      fullPath: '/dashboard/review'
      preLoaderRoute: typeof DashboardReviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kanban': {
      id: '/dashboard/kanban'
      path: '/kanban'
      fullPath: '/dashboard/kanban'
      preLoaderRoute: typeof DashboardKanbanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/focus': {
      id: '/dashboard/focus'
      path: '/focus'
      fullPath: '/dashboard/focus'
      preLoaderRoute: typeof DashboardFocusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/kanban/': {
      id: '/dashboard/kanban/'
      path: '/'
      fullPath: '/dashboard/kanban/'
      preLoaderRoute: typeof DashboardKanbanIndexRouteImport
      parentRoute: typeof DashboardKanbanRoute
    }
    '/dashboard/kanban/$boardId': {
      id: '/dashboard/kanban/$boardId'
      path: '/$boardId'
      fullPath: '/dashboard/kanban/$boardId'
      preLoaderRoute: typeof DashboardKanbanBoardIdRouteImport
      parentRoute: typeof DashboardKanbanRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardKanbanRouteChildren {
  DashboardKanbanBoardIdRoute: typeof DashboardKanbanBoardIdRoute
  DashboardKanbanIndexRoute: typeof DashboardKanbanIndexRoute
}

const DashboardKanbanRouteChildren: DashboardKanbanRouteChildren = {
  DashboardKanbanBoardIdRoute: DashboardKanbanBoardIdRoute,
  DashboardKanbanIndexRoute: DashboardKanbanIndexRoute,
}

const DashboardKanbanRouteWithChildren = DashboardKanbanRoute._addFileChildren(
  DashboardKanbanRouteChildren,
)

interface DashboardRouteChildren {
  DashboardFocusRoute: typeof DashboardFocusRoute
  DashboardKanbanRoute: typeof DashboardKanbanRouteWithChildren
  DashboardReviewRoute: typeof DashboardReviewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFocusRoute: DashboardFocusRoute,
  DashboardKanbanRoute: DashboardKanbanRouteWithChildren,
  DashboardReviewRoute: DashboardReviewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
